### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by rabberk** [cvlab-stonybrook/PathLDM#1]
Hello, there are close to 10,000 text reports in the link you provided, but in your arxiv article I see that you only used about 1,000 cases for fine-tuning, can I know why？

**Comment by srikarym** [comment]
TCGA contains Whole slide images and text reports of various cancer types. We train our models on the Breast Invasive Carcinoma (BRCA), which has ~ 1000 cases.

**Comment by rabberk** [comment]
noted，thanks for your explanation
