### ISSUE TITLE
can you please provide center_crop_real_stats.npz?

### ISSUE THREAD

**Issue by bhosalems** [cvlab-stonybrook/PathLDM#11]
Hi,

I am wondering if you can provide us with this file on train and test samples.
From the checkpoint, you provided I could get an FID score of 34.69049194608925 on the test split. According to https://github.com/cvlab-stonybrook/PathLDM/issues/9 should have been around 10.

**Comment by srikarym** [comment]
[Uploaded](https://drive.google.com/file/d/19GRhyINPKGNRkkW4mhYskFSwApwkq4Pd/view?usp=sharing)

**Comment by bhosalems** [comment]
Thanks, which split is it for?

**Comment by sjjadsa** [comment]
Hey,can u tell me what center_crop_real_stats.npz is for?

**Comment by bhosalems** [comment]
to calculate FID of generated samples. We need SD and variance of original samples.

**Comment by sjjadsa** [comment]
Thanks.I want to ask a question,During your training process, have you ever encountered the issue "RuntimeError: Found dtype Float but expected Half"? The error occurred in the line trainer.fit(model, data) within main.py.

**Comment by bhosalems** [comment]
Yes, I did. I had to do manual casting to float32.
