### ISSUE TITLE
"used GPT-3.5 to summarize them" details

### ISSUE THREAD

**Issue by trinhvg** [cvlab-stonybrook/PathLDM#12]
Hello,
Could you provide us with more details on how you used GPT-3.5 to summarize them? 
Did you manually input the prompts and text into ChatGPT, or did you have an automated process for this?
Thank you.

**Comment by srikarym** [comment]
We used the [OpenAI Python API](https://platform.openai.com/docs/quickstart?context=python) to automate this process. GPT variant was `gpt-3.5-turbo`

**Comment by trinhvg** [comment]
Thank you
