### ISSUE TITLE
Sample black images

### ISSUE THREAD

**Issue by Paulpey13** [cvlab-stonybrook/PathLDM#15]
Hello! First of all, I loved your paper; it is really an amazing work!

I wanted to test the model, so I built all the dependencies, downloaded the right configs, etc. However, when I execute the notebook (batch_size=2 because I don't have enough memory), every prompt generates black images. Have you ever had this problem? I don't know what to do.

Thank you in advance.

**Comment by srikarym** [comment]
I've never faced this issue. Could you replace `with torch.no_grad():` with `with torch.no_grad(), model.ema_scope():`

**Comment by Paulpey13** [comment]
Hello, thanks for your response. I ran the same code on another computer with better GPUs and more RAM, and the problem resolved automatically. It seems that my initial computer was lacking sufficient memory, I saw that it was a common problem with diffusions.
