### ISSUE TITLE
Model dtype, data dtype

### ISSUE THREAD

**Issue by AhmadObeid** [cvlab-stonybrook/PathLDM#16]
Hi, thank you authors for sharing your code with us.
I am facing the following error when attempting to run main.py with the same config file provided:
> RuntimeError: Found dtype Float but expected Half

This is similar to the problem discussed in issue #7, yet it has not been resolved.
Things I tried:
1) Made sure requirements are satisfied by creating the conda environment as instructed
2) Tried to convert the model to fp16 using model.half() or model.to(dtype=torch.float16) but I kept getting the error:
> RuntimeError: Input type (float) and bias type (c10::Half) should be the same

To that end, I also tried to make the data dtype the same by placing the line:
`image = torch.from_numpy(image).to(dtype=torch.float16)`
right before the return in the __get__item() of TCGADataset(), but to no avail.
3) I wanted to try using `torch.cuda.amp.autocast()`, but I discovered that it has been already implemented in ddpm.py line 1136:
```
with torch.cuda.amp.autocast():
                x_recon = self.model(x_noisy, t, **cond)
```
I really searched everywhere and couldn't find any solution. Your help would be greatly appreciated.

**Comment by AhmadObeid** [comment]
Update: I was able to overcome the error by:
1. In main.py, do: `model = model.half()`
2. In autoencoder.py, changed every input to any channel x to x.half()

The code finally runs, but as it stands, the loss is nan and doesn't seem to be changing, which makes me wonder the validity of the workaround I am suggesting. 

I understand that it is generally more advised to use the amp.autocast() method, but given that it is already used as is mentioned in my question above, I am not sure where else to place it in order to solve the main error, while avoiding divergence.

**Comment by srikarym** [comment]
You could also add `precision: 16` to the last line of the training config (additional argument to the pytorch lightning Trainer constructor)

https://pytorch-lightning.readthedocs.io/en/1.2.10/advanced/amp.html#gpu-16-bit

**Comment by windygoo** [comment]
> You could also add `precision: 16` to the last line of the training config (additional argument to the pytorch lightning Trainer constructor)
> 
> https://pytorch-lightning.readthedocs.io/en/1.2.10/advanced/amp.html#gpu-16-bit

adding this parameter raises another error:

RuntimeError: expected scalar type Half but found Float
