### ISSUE TITLE
"version: "vinid/plip",RuntimeError: Error(s) in loading state_dict for LatentDiffusion

### ISSUE THREAD

**Issue by sjjadsa** [cvlab-stonybrook/PathLDM#19]
Hi,authors
        In configs/latent-diffusion/text_cond/plip_imagenet_finetune.yaml,  model---params---cond_stage_config,there is a ""version: "vinid/plip"",I download this at https://huggingface.co/vinid/plip,but when I sampling with command "PYTHONPATH="./:${PYTHONPATH}" CUDA_VISIBLE_DEVICES=3 python sampling.py"
it shows error in the picture,is there something wrong?
![11BFF818B6DFC5671C46E578D3449E29](https://github.com/cvlab-stonybrook/PathLDM/assets/147935225/e9487bba-789c-4e44-8149-f3f6b88628a1)

**Comment by srikarym** [comment]
It looks like a warning, were you able to generate meaningful images?

**Comment by sjjadsa** [comment]
no，it didnt generate any images.Below is my vinid/plip folder,
![99CC75DD272A0C2D73E3189E80B493A6](https://github.com/cvlab-stonybrook/PathLDM/assets/147935225/799fe92f-e765-47fa-b643-393c59c4c700)

**Comment by sjjadsa** [comment]
Based on the code, it seems only the text encoder part of vinid/plip is loaded, which is why I'm getting a notification that the image encoder is not being used (as can be seen from the screenshot I attached in my comment). However, strangely, after the notification, the sampling.py script stops running, and I cannot find any output images in the files. Why is this happening?

**Comment by sjjadsa** [comment]
I know where the problem comes from. Since I was running the code on the server, I couldn't directly display the generated image. I modified the code to save the generated image to a folder, and the problem was solved. Thank you.
