### ISSUE TITLE
TCGA BRCA cropped Images?

### ISSUE THREAD

**Issue by bhosalems** [cvlab-stonybrook/PathLDM#2]
Hi authors, 

Thanks for releasing the code for publication.
 
to reproduce the results accurately I was wondering if it is possible to release steps for preprocessing TCGA  WSI Images and Tran/Test split.

**Comment by bhosalems** [comment]
Excuse me, I believe I can get Split from the summaries JSON that you provided on the drive, so please ignore that part of the question for now.

**Comment by srikarym** [comment]
Updated the [Readme](https://github.com/cvlab-stonybrook/PathLDM/tree/main?tab=readme-ov-file#downloading--organizing-data). We will upload the actual image patches and Tumor/TIL probabilities used in training soon.

**Comment by srikarym** [comment]
TCGA-BRCA Image patches, captions and Tumor/TIL probabilities used in our training can be downloaded from [this link](https://drive.google.com/drive/folders/1MPBsVjh7q57DzYJXSLF2wkKjssw3jEtF?usp=sharing).

**Comment by bhosalems** [comment]
Thank you.

**Comment by sjjadsa** [comment]
@bhosalems Did you download the hdf5 file in #2? Since the author has closed the download channel Google Drive no longer provides unlimited storage for edu accounts, can you share it with me?
