### ISSUE TITLE
del ckpt_path

### ISSUE THREAD

**Issue by sjjadsa** [cvlab-stonybrook/PathLDM#20]
I would like to ask the author a questiont:
      In the get_model function of example_sampling.ipynb, why are the checkpoint paths for both first_stage_config and UNet being removed, and instead, you are using plip_imagenet_finetune/checkpoints/epoch_3.ckpt?
      I would like to understand the reasoning behind this decision.Thank you！
![9440020906B28A51C31654E82B6747C9](https://github.com/cvlab-stonybrook/PathLDM/assets/147935225/95d99189-c856-448a-9776-9bd5481e6009)

**Comment by srikarym** [comment]
The checkpoints are ImageNet pretrained U-Net and VAE weights, needed to train the pathology diffusion model. For sampling, the weights we provide is self-sufficient, so these paths are not required.
