### ISSUE TITLE
wandb;visualization

### ISSUE THREAD

**Issue by sjjadsa** [cvlab-stonybrook/PathLDM#22]
I successfully completed the training by using the command python main.py --base configs/latent-diffusion/text_cond/plip_imagenet_finetune.yaml. Surprisingly, it didn't take too long, even though I was using an NVIDIA GeForce RTX 2080 SUPER graphics card. However, I didn't see any images similar to those mentioned in #17, and I only got these five files. Is it because I need to modify the code?
![994444E30457C47EB3F020384CC773ED](https://github.com/cvlab-stonybrook/PathLDM/assets/147935225/8ba053d5-da95-4fa5-bc21-e97b6b0f9ea5)

![A28BB460BFD15CD3BEFD37E75863ADE7](https://github.com/cvlab-stonybrook/PathLDM/assets/147935225/389dfe8e-aac8-4792-ba9d-cd771958ea0c)

**Comment by srikarym** [comment]
Yeah the code doesn't log images to wandb. It stores them in a local folder (logs/<exp_name>)
