### ISSUE TITLE
FID remained unchanged

### ISSUE THREAD

**Issue by sjjadsa** [cvlab-stonybrook/PathLDM#23]
![A3849FC04C1E6623A9D2BE7E5A3BA28F](https://github.com/cvlab-stonybrook/PathLDM/assets/147935225/bc7d9466-4b2f-4355-bf41-77be013772de)
Why does the FID remain unchanged during my training process? I'm using the dataset you provided in #2, and the config is plip_imagenet_finetune.yaml, where the unet and first_stage_config are the ones you provided in other issues.

**Comment by srikarym** [comment]
How many iterations did you train for?

**Comment by sjjadsa** [comment]
![image](https://github.com/cvlab-stonybrook/PathLDM/assets/147935225/2527546f-d169-4490-97c8-435a11cbf71a)
According to the workspace on the wandb webpage, the epoch is 531899

**Comment by srikarym** [comment]
that seems impossible, are you training on all 12 million images?

**Comment by sjjadsa** [comment]
![image](https://github.com/cvlab-stonybrook/PathLDM/assets/147935225/adab1296-3752-4ee5-bf87-fe888a01e0d7)
![image](https://github.com/cvlab-stonybrook/PathLDM/assets/147935225/8b985199-2193-49a8-bf55-8879f4bb8b5f)
![image](https://github.com/cvlab-stonybrook/PathLDM/assets/147935225/3cd138a8-4af5-4643-a393-ea20b923da49)
![image](https://github.com/cvlab-stonybrook/PathLDM/assets/147935225/d1f8f243-0fbb-44fd-99bb-054cff18d906)
This is the inside of my folder. It seems that the indices.til.npy file is missing from the test folder

**Comment by srikarym** [comment]
I believe you aren't using the actual training images. Completing 500k epochs doesn't make any sense to me.
