### ISSUE TITLE
About the structure of hdf5 cropped images file?

### ISSUE THREAD

**Issue by bhosalems** [cvlab-stonybrook/PathLDM#4]
Thank you for providing the dataset in the below issue,
https://github.com/cvlab-stonybrook/PathLDM/issues/2

I was wondering what is the structure of the Data provided. For example, I read the first five elements of each part of what looks like an image list, folder name, and UIDs.

```
def print_structure(name, obj):
    print(name)
    if isinstance(obj, h5py.Dataset):
        print(f" - Dataset, shape: {obj.shape}, type: {obj.dtype}")
file_name = 'TCGA_BRCA_10x_448_tumor.hdf5'

with h5py.File(file_name, 'r') as file:
    file.visititems(print_structure)

    # Reading first 5 elements of each dataset
    print("First 5 elements in X:", file['X'][:5])
    print("First 5 elements in folder_name:", file['folder_name'][:5])
    print("First 5 elements in wsi:", file['wsi'][:5])
```

And the output is,
```
X
 - Dataset, shape: (1283717,), type: object
folder_name
 - Dataset, shape: (1283717,), type: object
wsi
 - Dataset, shape: (1283717,), type: object
 - 
First 5 elements in X: [array([255, 216, 255, ..., 220, 255, 217], dtype=uint8)
 array([255, 216, 255, ...,  15, 255, 217], dtype=uint8)
 array([255, 216, 255, ..., 185, 255, 217], dtype=uint8)
 array([255, 216, 255, ..., 143, 255, 217], dtype=uint8)
 array([255, 216, 255, ..., 127, 255, 217], dtype=uint8)]
First 5 elements in folder_name: [b'14_9632_0' b'14_9408_224' b'14_9632_224' b'14_9856_224' b'14_10080_224']
First 5 elements in wsi: [b'TCGA-A1-A0SD-01Z-00-DX1' b'TCGA-A1-A0SD-01Z-00-DX1'
 b'TCGA-A1-A0SD-01Z-00-DX1' b'TCGA-A1-A0SD-01Z-00-DX1'
 b'TCGA-A1-A0SD-01Z-00-DX1']
```
 
 The size of the first Image, for example, is 36631, but it was said that the patches are of sizes 256*256. Let me know if I am missing something.

**Comment by srikarym** [comment]
[This file](https://github.com/cvlab-stonybrook/PathLDM/blob/main/ldm/data/text_cond/tumor_til_in_text.py) contains the dataset class we use for training. Each image in this hdf5 is a 448x448 patch @ 10x, from which we take a random crop of 256x256.

X contains the jpeg images encoded as bytes
wsi and folder_name contain the WSI name and area (X and Y location) of the patch. folder_name is not really important - it is how [DS-MIL](https://github.com/binli123/dsmil-wsi) organizes the patches after cropping.

**Comment by bhosalems** [comment]
Got it. Thanks.
