### ISSUE TITLE
name of the pretrained UNET checkpoint of cin256-v2?

### ISSUE THREAD

**Issue by bhosalems** [cvlab-stonybrook/PathLDM#5]
https://ommer-lab.com/files/latent-diffusion/nitro/cin.zip  I see that this path is being used in some notebooks online, although in the original latent diffusion github I could not find this path in download model scripts. I downloaded the weights but the default name of the file is model.ckpt, I just wanted to make sure if you just renamed this file to unet.ckpt?

**Comment by bhosalems** [comment]
I think the weight file was renamed because I can load the weights without any errors.

**Comment by srikarym** [comment]
Yeah this is the weights file of [Imagenet LDM](https://ommer-lab.com/files/latent-diffusion/nitro/cin/model.ckpt). We had to delete the class embedder weights from this ckpt, and change a couple of things in pytorch lightning's source code to allow fine-tuning
