### ISSUE TITLE
Will you be releasing Autoencoder wights as well with f=4?

### ISSUE THREAD

**Issue by bhosalems** [cvlab-stonybrook/PathLDM#6]
This i believe is a finetuned autoencoder on TCGA with f=4, I was wondering if you plan to release the weights from this, "models/first_stage_models/vq-f4-tcga-brca/last.ckpt"

**Comment by srikarym** [comment]
The finetuned VAE weights can be extracted from our [text conditional LDM](https://drive.google.com/drive/folders/1v3SXkA1D94w7Q1XMPSEA1yrSfpwhXzCr)

**Comment by bhosalems** [comment]
Thank you.

**Comment by zhtyolivia** [comment]
@bhosalems Were you able to extract VAE weights from the text condition LDM? Would you mind sharing your code to do that? Thank you!
