### ISSUE TITLE
Is environment.yaml updated?

### ISSUE THREAD

**Issue by bhosalems** [cvlab-stonybrook/PathLDM#7]
I am facing problems with transformers library, in particular w.r.t CLIPTokenizer. I was wondering if environment.yaml is up to date?

**Comment by bhosalems** [comment]
I can start the training now. There were a couple of things I had to change, if I can get the training correctly, I will update the yaml later.

**Comment by MeesMeuwissen** [comment]
I am wondering the same thing. Did you manage to fix things? I am still struggling.

**Comment by bhosalems** [comment]
I have managed to start the training but I have to check if I am able to reproduce the results.

**Comment by bhosalems** [comment]
@srikarym can you please update this? If I manage to train the model with other versions of Pytorch and lightning, after a few steps I get nan loss, I have tried multiple combinations of learning rate and batch sizes, but no luck.

But to work with the versions I have,  I had to downcast the tensors at two locations, otherwise, I am getting below error, and its hard to figure out why this is happening. 
```
  File "/home/csgrad/mbhosale/anaconda3/envs/pathldm1/lib/python3.8/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Found dtype Float but expected Half

```
To rule out the possibility of versions I want to make it same as what you guys have, thanks.

**Comment by srikarym** [comment]
Updated, also added the list of packages (output of `pip list`) to [pip_list.txt](./pip_list.txt)

**Comment by mQvQ** [comment]
> @srikarym can you please update this? If I manage to train the model with other versions of Pytorch and lightning, after a few steps I get nan loss, I have tried multiple combinations of learning rate and batch sizes, but no luck.
> 
> But to work with the versions I have, I had to downcast the tensors at two locations, otherwise, I am getting below error, and its hard to figure out why this is happening.
> 
> ```
>   File "/home/csgrad/mbhosale/anaconda3/envs/pathldm1/lib/python3.8/site-packages/torch/autograd/__init__.py", line 200, in backward
>     Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
> RuntimeError: Found dtype Float but expected Half
> ```
> 
> To rule out the possibility of versions I want to make it same as what you guys have, thanks.

I encountered the same error when training the model on my own dataset, and I am certain that I am using the same versions of PyTorch and PyTorch Lightning as the author. Could you provide more detailed information on how to solve this problem? Thank you.

**Comment by srikarym** [comment]
Convert model and input to fp16

**Comment by mraoaakash** [comment]
Could you provide further assistance? How do I go about making these changes? I have tried doing this, however there's no positive result. Could you provide any exact information on what needs to be changed? This would be greatly appreciated.

**Comment by mraoaakash** [comment]
Updating the model and input to fp16 still results in the same error. Converting model to half() and editing x and z in the ddpm scripts to half() gets the training to run, however, the losses are nan valued. I request you to provide an exact fix for the same.

**Comment by srikarym** [comment]
I'd suggest you to take a look at pytorch's documentation on mixed precision - https://pytorch.org/docs/stable/notes/amp_examples.html
