### ISSUE TITLE
FID scores reported in the paper on training set?

### ISSUE THREAD

**Issue by bhosalems** [cvlab-stonybrook/PathLDM#9]
Hi authors,

I had one question regarding the FID reported in the paper, is it on training reports as mentioned in the Limitation, it wasn't clear just by reading the experiments section and Limitations section, so I wanted to be sure.

**Comment by srikarym** [comment]
Yes, we obtained an FID ~ 10 on the test split

**Comment by bhosalems** [comment]
sorry, did you mean train split?

**Comment by bhosalems** [comment]
Oh ok, nvm, I see that train split is ~7. and you are saying on test split you got ~10.
